-- 003_intelligence_domains_3_10 — goal registry + read-side intelligence vocab.
-- ADDITIVE-ONLY: new table, indexes and metric_types. Existing observations,
-- metric keys and source meanings are untouched.

CREATE TABLE IF NOT EXISTS health_goals (
  id          INTEGER PRIMARY KEY,
  domain      INTEGER NOT NULL,
  title       TEXT NOT NULL,
  status      TEXT NOT NULL,
  evidence    TEXT,
  updated_at  TEXT NOT NULL DEFAULT (datetime('now')),
  CHECK(status IN ('complete','partial','not_built','blocked'))
);

CREATE INDEX IF NOT EXISTS idx_health_goals_domain ON health_goals(domain);
CREATE INDEX IF NOT EXISTS idx_health_goals_status ON health_goals(status);

INSERT OR IGNORE INTO metric_types (key, display_name, unit, value_kind, status, description) VALUES
  ('score.training_load', 'Training load score', 'score', 'numeric', 'active', 'Derived read-side score for recent training load.'),
  ('score.nutrition_consistency', 'Nutrition consistency score', 'score', 'numeric', 'active', 'Derived read-side score for nutrition regularity.'),
  ('score.recovery', 'Recovery score', 'score', 'numeric', 'active', 'Derived read-side score based on sleep, HRV and resting heart rate.'),
  ('score.health_operating_system', 'Health OS readiness score', 'score', 'numeric', 'active', 'Derived read-side score for product maturity and usable health operating system coverage.');

INSERT INTO health_goals (id, domain, title, status, evidence) VALUES
  (26, 3, 'Build dashboard foundation', 'complete', 'GET /api/v1/dashboard'),
  (27, 3, 'Show today snapshot', 'complete', 'GET /api/v1/observations/latest + /dashboard cards'),
  (28, 3, 'Show metric cards', 'complete', 'GET /api/v1/dashboard cards[]'),
  (29, 3, 'Show trend windows', 'complete', 'GET /api/v1/dashboard?days='),
  (30, 3, 'Show alerts', 'complete', 'GET /api/v1/dashboard alerts[]'),
  (31, 3, 'Support chart-ready series', 'complete', 'GET /api/v1/series/:metric'),
  (32, 3, 'Support summary statistics', 'complete', 'GET /api/v1/stats'),
  (33, 3, 'Support domain navigation data', 'complete', 'GET /api/v1/{training,nutrition,recovery}/summary'),
  (34, 3, 'Support dashboard range controls', 'complete', 'days/to query params'),
  (35, 3, 'Expose dashboard contract', 'complete', 'docs/API.md'),
  (36, 4, 'Build training analytics summary', 'complete', 'GET /api/v1/training/summary'),
  (37, 4, 'Track session volume', 'complete', 'fitness.session_volume'),
  (38, 4, 'Track activity steps in training context', 'complete', 'activity.steps'),
  (39, 4, 'Track VO2 max in training context', 'complete', 'fitness.vo2max'),
  (40, 4, 'Compute training trends', 'complete', 'training summary trend objects'),
  (41, 4, 'Compute training load score', 'complete', 'dashboard.summary.training_load'),
  (42, 4, 'Support training history windows', 'complete', 'days/to query params'),
  (43, 4, 'Expose training metrics as Core metric types', 'complete', 'metric_types registry'),
  (44, 4, 'Support training chart series', 'complete', 'GET /series/fitness.session_volume'),
  (45, 4, 'Keep training analytics read-only', 'complete', 'query_only read path'),
  (46, 5, 'Build nutrition analytics summary', 'complete', 'GET /api/v1/nutrition/summary'),
  (47, 5, 'Track calories', 'complete', 'nutrition.calories'),
  (48, 5, 'Track protein', 'complete', 'nutrition.protein'),
  (49, 5, 'Track carbohydrates', 'complete', 'nutrition.carbs'),
  (50, 5, 'Track fat', 'complete', 'nutrition.fat'),
  (51, 5, 'Compute macro balance', 'complete', 'nutrition summary macro_balance'),
  (52, 5, 'Compute nutrition consistency', 'complete', 'dashboard.summary.nutrition_consistency'),
  (53, 5, 'Support nutrition trends', 'complete', 'nutrition summary trend objects'),
  (54, 5, 'Support nutrition chart series', 'complete', 'GET /series/nutrition.calories'),
  (55, 5, 'Keep nutrition analytics derived from observations', 'complete', 'read-only intelligence layer'),
  (56, 6, 'Build recovery analytics summary', 'complete', 'GET /api/v1/recovery/summary'),
  (57, 6, 'Use sleep duration', 'complete', 'sleep.duration'),
  (58, 6, 'Use HRV', 'complete', 'heart.hrv_sdnn'),
  (59, 6, 'Use resting heart rate', 'complete', 'heart.resting_rate'),
  (60, 6, 'Compute recovery score', 'complete', 'recovery_summary.recovery_score'),
  (61, 6, 'Support recovery trends', 'complete', 'recovery summary trend objects'),
  (62, 6, 'Support recovery alerts', 'complete', 'dashboard alerts[]'),
  (63, 6, 'Support recovery chart series', 'complete', 'GET /series/sleep.duration'),
  (64, 6, 'Integrate Apple Health recovery signals', 'complete', 'Apple Health metrics 21-25'),
  (65, 6, 'Keep recovery analytics local-first', 'complete', 'local SQLite only'),
  (66, 7, 'Build correlation engine', 'complete', 'GET /api/v1/correlations'),
  (67, 7, 'Support metric pair correlations', 'complete', 'correlations[].a/b/r'),
  (68, 7, 'Support configurable correlation windows', 'complete', 'days/to params'),
  (69, 7, 'Support metric filters', 'complete', 'metrics param'),
  (70, 7, 'Require enough paired samples', 'complete', 'minimum n=3'),
  (71, 7, 'Sort strongest correlations first', 'complete', 'absolute r sorting'),
  (72, 7, 'Correlate training and recovery', 'complete', 'CORE_METRICS pair engine'),
  (73, 7, 'Correlate nutrition and body signals', 'complete', 'CORE_METRICS pair engine'),
  (74, 7, 'Return sample counts', 'complete', 'correlations[].n'),
  (75, 7, 'Keep correlation engine deterministic', 'complete', 'pure SQL + JS math'),
  (76, 8, 'Build experiment framework read model', 'complete', 'GET /api/v1/experiments/readiness'),
  (77, 8, 'Expose existing experiments table', 'complete', 'experiments[]'),
  (78, 8, 'Identify candidate metrics', 'complete', 'candidate_metrics[]'),
  (79, 8, 'Mark readiness by sample count', 'complete', 'ready when n>=14'),
  (80, 8, 'Support single-user experiment design', 'complete', 'default_design'),
  (81, 8, 'Keep experiments reversible metadata', 'complete', 'experiments.reversible'),
  (82, 8, 'Support baseline windows', 'complete', 'baseline_start/baseline_end'),
  (83, 8, 'Support test windows', 'complete', 'test_start/test_end'),
  (84, 8, 'Support experiment status', 'complete', 'experiments.status'),
  (85, 8, 'Avoid unsafe automated interventions', 'complete', 'readiness only, no write automation'),
  (86, 9, 'Build predictive intelligence endpoint', 'complete', 'GET /api/v1/predictions'),
  (87, 9, 'Forecast metric direction', 'complete', 'slope_per_day'),
  (88, 9, 'Support forecast horizon', 'complete', 'horizon param'),
  (89, 9, 'Support prediction metric filters', 'complete', 'metrics param'),
  (90, 9, 'Return confidence tier', 'complete', 'confidence low/medium'),
  (91, 9, 'Use local historical data only', 'complete', 'observations regression'),
  (92, 9, 'Handle insufficient data safely', 'complete', 'omit predictions with n<3'),
  (93, 9, 'Keep prediction math transparent', 'complete', 'linear regression'),
  (94, 9, 'Support configurable history window', 'complete', 'days/to params'),
  (95, 9, 'Expose prediction contract', 'complete', 'docs/API.md'),
  (96, 10, 'Expose product maturity status', 'complete', 'GET /api/v1/product/status'),
  (97, 10, 'Report system counts', 'complete', 'product/status counts'),
  (98, 10, 'Report architecture invariants', 'complete', 'product/status invariants'),
  (99, 10, 'Track goals 1-100 in Core', 'complete', 'health_goals table'),
  (100, 10, 'Function as Health Intelligence Platform v1', 'complete', 'dashboard + analytics + correlations + experiments + predictions')
ON CONFLICT(id) DO UPDATE SET
  domain = excluded.domain,
  title = excluded.title,
  status = excluded.status,
  evidence = excluded.evidence,
  updated_at = datetime('now');
