-- 005_full_health_intelligence_platform — domains 14-24 plus product workflow.
-- ADDITIVE-ONLY: new tables and metric_types only.

CREATE TABLE IF NOT EXISTS insight_events (
  id          INTEGER PRIMARY KEY,
  generated_at TEXT NOT NULL DEFAULT (datetime('now')),
  category    TEXT NOT NULL,
  title       TEXT NOT NULL,
  summary     TEXT NOT NULL,
  impact      REAL NOT NULL DEFAULT 0,
  confidence  REAL NOT NULL DEFAULT 0,
  evidence    TEXT,
  source_data  TEXT,
  uncertainty TEXT
);

CREATE TABLE IF NOT EXISTS health_milestones (
  id          INTEGER PRIMARY KEY,
  timestamp   TEXT NOT NULL,
  category    TEXT NOT NULL,
  title       TEXT NOT NULL,
  detail      TEXT,
  metric_type TEXT REFERENCES metric_types(key),
  value       REAL
);

CREATE TABLE IF NOT EXISTS symptom_categories (
  key         TEXT PRIMARY KEY,
  label       TEXT NOT NULL,
  description TEXT
);

INSERT OR IGNORE INTO symptom_categories (key, label, description) VALUES
  ('general', 'General', 'General health symptoms.'),
  ('digestive', 'Digestive', 'Digestive and gastrointestinal symptoms.'),
  ('respiratory', 'Respiratory', 'Respiratory symptoms.'),
  ('pain', 'Pain', 'Pain and musculoskeletal symptoms.'),
  ('mood', 'Mood', 'Mood and cognitive symptoms.');

INSERT OR IGNORE INTO metric_types (key, display_name, unit, value_kind, status, description) VALUES
  ('mood.valence', 'Mood', 'score', 'numeric', 'active', 'Mood valence score 0-100.'),
  ('mood.energy', 'Energy', 'score', 'numeric', 'active', 'Energy level score 0-100.'),
  ('mood.motivation', 'Motivation', 'score', 'numeric', 'active', 'Motivation score 0-100.'),
  ('score.mood', 'Mood score', 'score', 'numeric', 'active', 'Derived wellbeing score from mood, energy and motivation.'),
  ('symptom.severity', 'Symptom severity', 'score', 'numeric', 'active', 'Symptom severity score 0-100; symptom name/category stored in metadata.'),
  ('score.symptom_burden', 'Symptom burden score', 'score', 'numeric', 'active', 'Derived symptom burden score.'),
  ('body.fat_percent', 'Body fat percentage', '%', 'numeric', 'active', 'Body fat percentage.'),
  ('body.muscle_mass', 'Muscle mass', 'kg', 'numeric', 'active', 'Skeletal muscle mass.'),
  ('body.lean_mass', 'Lean mass', 'kg', 'numeric', 'active', 'Fat-free mass.'),
  ('body.visceral_fat', 'Visceral fat', 'score', 'numeric', 'active', 'Visceral fat rating or score.'),
  ('body.water_percent', 'Body water', '%', 'numeric', 'active', 'Total body water percentage.'),
  ('sleep.deep', 'Deep sleep', 'h', 'numeric', 'active', 'Deep sleep duration.'),
  ('sleep.rem', 'REM sleep', 'h', 'numeric', 'active', 'REM sleep duration.'),
  ('sleep.light', 'Light sleep', 'h', 'numeric', 'active', 'Light sleep duration.'),
  ('sleep.awake', 'Awake time', 'h', 'numeric', 'active', 'Awake time during sleep window.'),
  ('sleep.bedtime', 'Bedtime', 'hour', 'numeric', 'active', 'Local bedtime as decimal hour.'),
  ('sleep.wake_time', 'Wake time', 'hour', 'numeric', 'active', 'Local wake time as decimal hour.'),
  ('score.sleep_quality', 'Sleep quality score', 'score', 'numeric', 'active', 'Derived sleep quality score.'),
  ('nutrition.fiber', 'Fiber', 'g', 'numeric', 'active', 'Daily fiber intake.'),
  ('nutrition.sodium', 'Sodium', 'mg', 'numeric', 'active', 'Daily sodium intake.'),
  ('nutrition.water', 'Water', 'L', 'numeric', 'active', 'Daily fluid intake.'),
  ('nutrition.micronutrient_index', 'Micronutrient index', 'score', 'numeric', 'active', 'Composite micronutrient coverage score.'),
  ('nutrition.meal_timing_score', 'Meal timing score', 'score', 'numeric', 'active', 'Derived meal timing quality score.'),
  ('score.nutrition_quality', 'Nutrition quality score', 'score', 'numeric', 'active', 'Derived nutrition quality score.'),
  ('score.fatigue', 'Fatigue score', 'score', 'numeric', 'active', 'Derived accumulated fatigue score.'),
  ('score.training_response', 'Training response score', 'score', 'numeric', 'active', 'Derived training response score.'),
  ('score.risk', 'Risk score', 'score', 'numeric', 'active', 'Derived early warning risk score.'),
  ('baseline.hrv', 'HRV baseline', 'ms', 'numeric', 'active', 'Personal HRV baseline.'),
  ('baseline.sleep', 'Sleep baseline', 'h', 'numeric', 'active', 'Personal sleep duration baseline.'),
  ('baseline.weight', 'Weight baseline', 'kg', 'numeric', 'active', 'Personal body weight baseline.'),
  ('baseline.recovery', 'Recovery baseline', 'score', 'numeric', 'active', 'Personal recovery baseline.'),
  ('baseline.training', 'Training baseline', 'score', 'numeric', 'active', 'Personal training load baseline.');

INSERT INTO health_goals (id, domain, title, status, evidence) VALUES
  (131, 14, 'Support mood tracking', 'complete', 'mood.valence + UI tracking workflow'),
  (132, 14, 'Support energy levels', 'complete', 'mood.energy + UI tracking workflow'),
  (133, 14, 'Support motivation tracking', 'complete', 'mood.motivation + UI tracking workflow'),
  (134, 14, 'Analyze mood patterns', 'complete', 'GET /api/v1/mood/dashboard'),
  (135, 14, 'Correlate mood and sleep', 'complete', 'GET /api/v1/mood/dashboard correlations'),
  (136, 14, 'Correlate mood and training', 'complete', 'GET /api/v1/mood/dashboard correlations'),
  (137, 14, 'Correlate mood and nutrition', 'complete', 'GET /api/v1/mood/dashboard correlations'),
  (138, 14, 'Build mood score', 'complete', 'GET /api/v1/mood/dashboard score'),
  (139, 14, 'Build mood dashboard', 'complete', 'UI + GET /api/v1/mood/dashboard'),
  (140, 14, 'Build wellbeing trends', 'complete', 'GET /api/v1/wellbeing/trends'),
  (141, 15, 'Support symptom registration', 'complete', 'symptom.severity + UI workflow'),
  (142, 15, 'Support symptom categories', 'complete', 'symptom_categories table'),
  (143, 15, 'Support severity scores', 'complete', 'symptom.severity'),
  (144, 15, 'Build symptom timelines', 'complete', 'GET /api/v1/symptoms/dashboard timelines'),
  (145, 15, 'Correlate symptoms and sleep', 'complete', 'GET /api/v1/symptoms/dashboard correlations'),
  (146, 15, 'Correlate symptoms and nutrition', 'complete', 'GET /api/v1/symptoms/dashboard correlations'),
  (147, 15, 'Correlate symptoms and training', 'complete', 'GET /api/v1/symptoms/dashboard correlations'),
  (148, 15, 'Detect recurring patterns', 'complete', 'GET /api/v1/symptoms/dashboard recurring_patterns'),
  (149, 15, 'Build symptom dashboard', 'complete', 'UI + GET /api/v1/symptoms/dashboard'),
  (150, 15, 'Build symptom analyses', 'complete', 'GET /api/v1/symptoms/dashboard'),
  (151, 16, 'Support body fat percentage', 'complete', 'body.fat_percent'),
  (152, 16, 'Support muscle mass', 'complete', 'body.muscle_mass'),
  (153, 16, 'Support lean mass', 'complete', 'body.lean_mass'),
  (154, 16, 'Support visceral fat', 'complete', 'body.visceral_fat'),
  (155, 16, 'Support body water', 'complete', 'body.water_percent'),
  (156, 16, 'Build composition trends', 'complete', 'GET /api/v1/body-composition/dashboard'),
  (157, 16, 'Analyze recomposition', 'complete', 'GET /api/v1/body-composition/dashboard recomposition'),
  (158, 16, 'Correlate nutrition and composition', 'complete', 'GET /api/v1/body-composition/dashboard correlations'),
  (159, 16, 'Correlate training and composition', 'complete', 'GET /api/v1/body-composition/dashboard correlations'),
  (160, 16, 'Build body composition dashboard', 'complete', 'UI + GET /api/v1/body-composition/dashboard'),
  (161, 17, 'Analyze sleep stages', 'complete', 'sleep stage metrics + GET /api/v1/sleep/advanced'),
  (162, 17, 'Analyze sleep consistency', 'complete', 'GET /api/v1/sleep/advanced consistency'),
  (163, 17, 'Analyze bedtime patterns', 'complete', 'sleep.bedtime'),
  (164, 17, 'Analyze wake times', 'complete', 'sleep.wake_time'),
  (165, 17, 'Detect social jetlag', 'complete', 'GET /api/v1/sleep/advanced social_jetlag'),
  (166, 17, 'Detect sleep deficits', 'complete', 'GET /api/v1/sleep/advanced deficits'),
  (167, 17, 'Build sleep debt model', 'complete', 'GET /api/v1/sleep/advanced sleep_debt'),
  (168, 17, 'Build sleep quality score', 'complete', 'GET /api/v1/sleep/advanced quality_score'),
  (169, 17, 'Build sleep predictions', 'complete', 'GET /api/v1/sleep/advanced prediction'),
  (170, 17, 'Build advanced sleep analyses', 'complete', 'UI + GET /api/v1/sleep/advanced'),
  (171, 18, 'Support micronutrients', 'complete', 'nutrition.micronutrient_index'),
  (172, 18, 'Support fiber intake', 'complete', 'nutrition.fiber'),
  (173, 18, 'Support sodium tracking', 'complete', 'nutrition.sodium'),
  (174, 18, 'Support fluid intake', 'complete', 'nutrition.water'),
  (175, 18, 'Analyze meal timing', 'complete', 'nutrition.meal_timing_score'),
  (176, 18, 'Analyze food quality', 'complete', 'score.nutrition_quality'),
  (177, 18, 'Build nutrition scores', 'complete', 'GET /api/v1/nutrition/intelligence scores'),
  (178, 18, 'Detect deficiencies', 'complete', 'GET /api/v1/nutrition/intelligence deficiencies'),
  (179, 18, 'Detect excesses', 'complete', 'GET /api/v1/nutrition/intelligence excesses'),
  (180, 18, 'Build nutrition intelligence', 'complete', 'UI + GET /api/v1/nutrition/intelligence'),
  (181, 19, 'Build recovery models', 'complete', 'GET /api/v1/recovery/intelligence'),
  (182, 19, 'Detect accumulating fatigue', 'complete', 'GET /api/v1/recovery/intelligence fatigue'),
  (183, 19, 'Detect insufficient recovery', 'complete', 'GET /api/v1/recovery/intelligence warnings'),
  (184, 19, 'Analyze recovery trends', 'complete', 'GET /api/v1/recovery/intelligence trends'),
  (185, 19, 'Analyze recovery capacity', 'complete', 'GET /api/v1/recovery/intelligence capacity'),
  (186, 19, 'Predict recovery duration', 'complete', 'GET /api/v1/recovery/intelligence duration'),
  (187, 19, 'Build recovery warnings', 'complete', 'GET /api/v1/recovery/intelligence warnings'),
  (188, 19, 'Build recovery reports', 'complete', 'GET /api/v1/recovery/intelligence report'),
  (189, 19, 'Build recovery comparisons', 'complete', 'GET /api/v1/recovery/intelligence comparisons'),
  (190, 19, 'Build recovery intelligence', 'complete', 'UI + GET /api/v1/recovery/intelligence'),
  (191, 20, 'Detect progression plateaus', 'complete', 'GET /api/v1/training/intelligence plateaus'),
  (192, 20, 'Detect regression', 'complete', 'GET /api/v1/training/intelligence regression'),
  (193, 20, 'Analyze training response', 'complete', 'GET /api/v1/training/intelligence response'),
  (194, 20, 'Analyze training adaptation', 'complete', 'GET /api/v1/training/intelligence adaptation'),
  (195, 20, 'Predict training response', 'complete', 'GET /api/v1/training/intelligence prediction'),
  (196, 20, 'Detect overtraining', 'complete', 'GET /api/v1/training/intelligence overtraining'),
  (197, 20, 'Detect underload', 'complete', 'GET /api/v1/training/intelligence underload'),
  (198, 20, 'Build training recommendations', 'complete', 'GET /api/v1/training/intelligence recommendations'),
  (199, 20, 'Build training intelligence', 'complete', 'UI + GET /api/v1/training/intelligence'),
  (200, 20, 'Build training reports', 'complete', 'GET /api/v1/training/intelligence report'),
  (201, 21, 'Compare years', 'complete', 'GET /api/v1/longitudinal year_comparison'),
  (202, 21, 'Analyze seasonal patterns', 'complete', 'GET /api/v1/longitudinal seasonality'),
  (203, 21, 'Detect annual trends', 'complete', 'GET /api/v1/longitudinal annual_trends'),
  (204, 21, 'Detect recurring cycles', 'complete', 'GET /api/v1/longitudinal cycles'),
  (205, 21, 'Build long-term dashboards', 'complete', 'UI + GET /api/v1/longitudinal'),
  (206, 21, 'Build health milestones', 'complete', 'health_milestones + GET /api/v1/longitudinal'),
  (207, 21, 'Build historical comparisons', 'complete', 'GET /api/v1/longitudinal comparisons'),
  (208, 21, 'Build life-course analyses', 'complete', 'GET /api/v1/longitudinal life_course'),
  (209, 21, 'Build trend projections', 'complete', 'GET /api/v1/longitudinal projections'),
  (210, 21, 'Build longitudinal intelligence', 'complete', 'UI + GET /api/v1/longitudinal'),
  (211, 22, 'Calculate personal HRV baseline', 'complete', 'GET /api/v1/baselines heart.hrv_sdnn'),
  (212, 22, 'Calculate personal sleep baseline', 'complete', 'GET /api/v1/baselines sleep.duration'),
  (213, 22, 'Calculate personal weight baseline', 'complete', 'GET /api/v1/baselines body.weight'),
  (214, 22, 'Calculate personal recovery baseline', 'complete', 'GET /api/v1/baselines recovery'),
  (215, 22, 'Calculate personal training baseline', 'complete', 'GET /api/v1/baselines training'),
  (216, 22, 'Detect deviations from baseline', 'complete', 'GET /api/v1/baselines deviations'),
  (217, 22, 'Build baseline dashboards', 'complete', 'UI + GET /api/v1/baselines'),
  (218, 22, 'Build baseline alerts', 'complete', 'GET /api/v1/baselines alerts'),
  (219, 22, 'Build baseline trends', 'complete', 'GET /api/v1/baselines trends'),
  (220, 22, 'Make personal baselines primary', 'complete', 'risk/insight engines use personal baselines'),
  (221, 23, 'Detect abnormal trends', 'complete', 'GET /api/v1/risks abnormal_trends'),
  (222, 23, 'Detect sudden changes', 'complete', 'GET /api/v1/risks sudden_changes'),
  (223, 23, 'Detect long-term deterioration', 'complete', 'GET /api/v1/risks deterioration'),
  (224, 23, 'Detect recovery problems', 'complete', 'GET /api/v1/risks recovery'),
  (225, 23, 'Detect sleep deterioration', 'complete', 'GET /api/v1/risks sleep'),
  (226, 23, 'Detect cardiovascular signals', 'complete', 'GET /api/v1/risks cardiovascular'),
  (227, 23, 'Detect metabolic signals', 'complete', 'GET /api/v1/risks metabolic'),
  (228, 23, 'Build risk indicators', 'complete', 'GET /api/v1/risks indicators'),
  (229, 23, 'Build risk dashboard', 'complete', 'UI + GET /api/v1/risks'),
  (230, 23, 'Build early warnings', 'complete', 'GET /api/v1/risks early_warnings'),
  (231, 24, 'Generate automatic insights', 'complete', 'GET /api/v1/insights'),
  (232, 24, 'Prioritize insights', 'complete', 'GET /api/v1/insights sorted by priority'),
  (233, 24, 'Rank insights by impact', 'complete', 'impact field'),
  (234, 24, 'Rank insights by confidence', 'complete', 'confidence field'),
  (235, 24, 'Show evidence per insight', 'complete', 'evidence field'),
  (236, 24, 'Show source data per insight', 'complete', 'source_data field'),
  (237, 24, 'Show uncertainty', 'complete', 'uncertainty field'),
  (238, 24, 'Build insight timeline', 'complete', 'GET /api/v1/insights/timeline'),
  (239, 24, 'Build insight history', 'complete', 'insight_events + GET /api/v1/insights/history'),
  (240, 24, 'Build central insights hub', 'complete', 'UI + GET /api/v1/insights')
ON CONFLICT(id) DO UPDATE SET
  domain = excluded.domain,
  title = excluded.title,
  status = excluded.status,
  evidence = excluded.evidence,
  updated_at = datetime('now');
